### ISSUE TITLE
CLOAD does not work with disk controler

### ISSUE THREAD

**Issue by assinie** [pete-gordon/oricutron#115]
Bug reported by kiwilevrai on french forum http://forums.oric.org:
When using Jasmin or Microdisc, CLOAD instruction is broken never find the tape file.
Same when using Telestrat.

I found why and I can prepare a PR but I have a question in order to do it the right way:

- what is the difference between oric->romon and oric->romdis and why not use only one?

**Comment by polluks** [comment]
@assinie They are not identical because of `oric->pravetz.olay`, romon is machine independent.
