### ISSUE TITLE
Oricutron crashs when we try to read Data register from 6551

### ISSUE THREAD

**Issue by jedeoric** [pete-gordon/oricutron#116]
lda $031c ; this will crash Oricutron

all others ACIA registers seems to work.

**Comment by jedeoric** [comment]
Assinie found the problem : 

in oricutron.cfg, when you have : 
serial = 'com:9600,8,N,1,COM5'

If COM5 does not exist then PRINT PEEK(#31C) will crash (only in telestrat mode)

**Comment by assinie** [comment]
One more thing, when the emulated machine is restarted when switching to another model or by using [F4] key, oric->acia is defaulting to ACIA_TYPE_NONE and not initialized so acia->get_byte() is null pointer even if the emulated machine is a Telestrat

**Comment by iss000** [comment]
@assinie: This is obvious a bug ;). I will try to fix it asap, but if you have already solution - just send it.
@jedeoric: I'll test and will fix the crash, but what should be the best solution for cases like this one? I vote for simple fall back to serial='none' :).

**Comment by assinie** [comment]
I think we can't have serial='none' with Telestrat because the acia struct will not be correctly initialized and the Telestrat own an ACIA.
I suggest fall back to serial=loopback with Telestrat otherwise serial=none.

**Comment by iss000** [comment]
I've just hit this bug and it's fixed with 6cfa1c2.

**Comment by jedeoric** [comment]
Thanks :)
