### ISSUE TITLE
[telestrat][bug] Setting hardware to Telestrat will crash the emulator

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [pete-gordon/oricutron#125]
Setting hardware to Telestrat will crash the emulator (tested under Windows 10)

I have also tried to set the hardware in the cfg file and select the rom images but I still get an immediate crash.

How do I start the Telestrat emulation? Is this a bug?

**Comment by pete-gordon** [comment]
This bug was fixed a long time ago in the git repo, but it has been far too long since I made a release. Sorry about that.

**Comment by Fabrizio-Caruso** [comment]
Could you please make a Windows binary available? It seems like a serious issue that deserves a release.

**Comment by polluks** [comment]
See #103
