### ISSUE TITLE
8dos2.rom not found error message, because there is no 8dos2.rom in the roms folder.

### ISSUE THREAD

**Issue by Blonder** [pete-gordon/oricutron#143]
In commit 7bc6a03e08b1687958b96dc0947391e16a4ce30f the line `strcpy( pravetzromfile[1], ROMPREFIX"8dos2" );` was added but there is no 8dos2.rom in he roms folder. Is the 2 a mistake? Or forgot to add 8dos2.rom to the roms folder.

**Comment by iss000** [comment]
@Blonder: Here you are:
[8D-roms.zip](https://github.com/pete-gordon/oricutron/files/3799269/8D-roms.zip)

It's not mistake. In the zip-file you'll find 2 version of the rom. '8dos2'  is the never one and has some code which is used with new DOS-8D versions.
