### ISSUE TITLE
function shut in machine.c and main.c should be static,

### ISSUE THREAD

**Issue by Blonder** [pete-gordon/oricutron#145]
implementation of shut in machine.c is missing that causes errors on some compilers.

**Comment by polluks** [comment]
Indeed, gcc6 fails.

**Comment by Blonder** [comment]
In 687d1eafe29701364c140b9476e8d9920b1638be I added static and empty implementation.

**Comment by Blonder** [comment]
On WSL with Ubuntu and gcc-6 (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026 it compiles fine (with some warnings).

**Comment by polluks** [comment]
@Blonder Hmm, why do we need this empty function at all?
Right now the MorphOS port is hanging at startup :(

**Comment by iss000** [comment]
IMO, the best is to leave 'shut' as is (i.e. public), add its prototype in 'main.h' and call it from 'machine.c' with proper parameters.

**Comment by iss000** [comment]
BTW, Linux port hangs too! What is interesting only SDL hangs, SDL2 works!

**Comment by iss000** [comment]
fixed in 606cb80
