### ISSUE TITLE
Oricutron hangs after introducing 'context'

### ISSUE THREAD

**Issue by iss000** [pete-gordon/oricutron#146]
After 3e9c08f which introduce 'context' structure Oricutron hangs under:
- Linux SDL (SDL2 build seams to work)
- MorphOS

**Comment by Blonder** [comment]
Sorry I can't test MorphOS because I haven't installed it.
On Ubuntu WSL with gcc-6 and SDL2 there is no problem.
Did you see any error message?

**Comment by Blonder** [comment]
If I compile with gcc-6 and SDL run into a seg fault when SDL_BuildAudioCVT  is called in 8912.c
After commenting out this call I can confirm that Oricutron hangs, I reverted the commit and commented out the SDL_BuildAudioCVT and Oricutron starts. So there is some woodhead error is this commit.

**Comment by iss000** [comment]
2928200 works for me:
![2928200](https://user-images.githubusercontent.com/1128663/68149058-dc93a280-ff45-11e9-9467-e1cb747eff64.png)

606cb80 (currently the last commit) don't work:
![606cb80](https://user-images.githubusercontent.com/1128663/68149257-3b591c00-ff46-11e9-9b7c-725a7308efb4.png)
Red mak shows no render is called.

**Comment by Blonder** [comment]
Did this commit fix it? ccf82f14efa184d02799505c8268a145cf86ec5e

**Comment by iss000** [comment]
No, it hangs in the same way.

**Comment by Blonder** [comment]
O.k. there were two errors the second I fixed in 71a647767407acf926347a9e6abba34950dc9b49

**Comment by Blonder** [comment]
Sorry for this, was too greedy yesterday.

**Comment by iss000** [comment]
Kein problem, spass muss sein! ;)
