### ISSUE TITLE
Unrechable code warnings when compiling

### ISSUE THREAD

**Issue by 0ric1** [pete-gordon/oricutron#147]
`filereq_sdl.c` or `msgbox_sdl.c` with Visual Studio 2019 16.4.0 Preview 4.0
`  SDL_COMPAT_EnableUNICODE( wasunicode );
  SDL_COMPAT_EnableKeyRepeat( wasunicode ? SDL_DEFAULT_REPEAT_DELAY : 0, wasunicode ? SDL_DEFAULT_REPEAT_INTERVAL : 0 );
  return SDL_FALSE;
`

**Comment by assinie** [comment]
Do you have the warnings by compiling with the SDL v1 and SDL v2 library or only with one of the 2 versions?

**Comment by 0ric1** [comment]
I am compiling with the SDL2.lib but I think it's independent of it, there is a `  for( ;; )
` loop in line 176 and in this loop there is a if and a switch where return SDL_TRUE/FALSE is called. The mentioned code in my first post is never ever called, so there is something in the switch wrong or the code can be removed completely.

**Comment by iss000** [comment]
@0ric1: can you paste the part with the warning from compile log?

**Comment by 0ric1** [comment]
`1>oricutron\msgbox_sdl.c(292): warning C4702: unreachable code
1>oricutron\msgbox_sdl.c(293): warning C4702: unreachable code
1>oricutron\msgbox_sdl.c(294): warning C4702: unreachable code
1>oricutron\filereq_sdl.c(753): warning C4702: unreachable code
1>oricutron\filereq_sdl.c(754): warning C4702: unreachable code
1>oricutron\filereq_sdl.c(755): warning C4702: unreachable code
`

**Comment by iss000** [comment]
Fixed with commit f22aac2.
