### ISSUE TITLE
When starting Oricutron I get roms errors / warnings ...

### ISSUE THREAD

**Issue by 0ric1** [pete-gordon/oricutron#170]
e.g. bd500.rom, even when I selected "No disk" in the hardware options.

**Comment by iss000** [comment]
Because of potential legal issues the roms/ directory doesn't contain any binary rom files.
This is the main reason for my developer builds. Download any file [from my site](https://iss.sandacite.com/oricutron/), extract it and copy what you need ;).

**Comment by 0ric1** [comment]
I use the roms shipped with the OSDK but there is no bd500.rom, seems to be that it was added and I missed it. But why is it loaded when it is not enabled? When I rename e.g. the jasmin.rom in the OSDK and start Oricutron from the OSDK no error message box appears. When it is not there the menu entry "Jasmin" in the Hardware menu is disabled.

**Comment by 0ric1** [comment]
@jedeoric  Why did you add !/roms/orix*.rom into .gitignore in revision 120871f8f837b35f4fb902c34fce789c033f24a5 ?

**Comment by iss000** [comment]
@0ric1 : Please, take some time to get more familiar with the Oricutron sources content. There are two types of ROM in regard of their copyright - BASIC, MICRODISK, JASMIN etc., which can't be freely distributed and other free (even open source) like **orix*.rom** which author is @jedeoric  and he can do whatever he wants with this file.
Else, did you check the Oricutron version in the OSDK? It's old 1.2 stable - at that time there was absolutely no idea to support bd500 drive.
Your activity is great but I highly recommend to use Pull Requests instead directly committing to the master branch.

**Comment by 0ric1** [comment]
@iss000 I thought BASIC etc. were also free because they are shipped with the OSDK. I asked about the orix.rom* because it is not commited but in the .gitignore it is marked with an negation "!" character so when it not there (when you first check out the repository) it is marked as non versioned, maybe you have not seen this because you have this rom in place.
Yes I did check the old 1.2 stable version. You can reproduce both problems (non versioned file and popping up dialog) when you temporary delete the bd500.rom and the orix.rom. 
I did some branches and pull request but that was too much work so I decided to work on the master (I known it's not a good way but I wanted to get rid of the code this weekend). And yes you are right, I should have squashed some changes (I do this actually with the next commit) but didn't with the last ounces because I only wanted to get it compile able with cmake again because of missing oric_twilighte_board_plugin.c (that I committed first) but then I saw it did not compile on the Pi400 with Buster 10, so I committed that patch but then I saw oric_twilighte_board_plugin.c is also missing in the vcxproj file, than I saw the header is also missing,  than I added the filter in the project for the plugins than I saw the email adress was changed but not in all places ... and that resulted in the various commits (this wasn't my intention), so sorry for this. At the moment I work again in the CMakeList.txt file to get the version and copyright info to the top and correct the .rc file and update the ReadMeNinjaCMakeBuild.md documentation file, but for this I am doing one branch and pull request.
