### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by LordEvyl** [pete-gordon/oricutron#185]
Does this emulator have a built-in screen capture command like a lot of other emulators for other computers and consoles have? If so, what is it, I cannot find it in the menu

**Comment by pete-gordon** [comment]
Hi,

Yes, pressing F10 will start and stop capturing to AVI video files. This is covered in the readme.


Cheers,
Pete

**Comment by LordEvyl** [comment]
Yeah, but I'm looking for still images, not videos

**Comment by polluks** [comment]
Well, simply use your OS for still images.

**Comment by iss000** [comment]
> Yes, pressing F10 will start and stop capturing to AVI video files. This is covered in the readme.
@pete-gordon: It seams you forgot your source ;)
There is [SDLK_PRINT](https://github.com/pete-gordon/oricutron/blob/461b2890132ee33ed686a650058997addd3cfaee/machine.c#L1537
) usage i.e. **Print-Screen key will save a .BMP file.**
