### ISSUE TITLE
How are .dsk files passed to OricutronJS upon clicking link to oricutron.html?

### ISSUE THREAD

**Issue by jumpjack** [pete-gordon/oricutron#186]
I can't understand  How .dsk files are  passed to OricutronJS upon clicking a link to oricutron.html; I know how  to load a .dsk file from local hard disk or remote server, and I would like to pass it to the emulator.

**Comment by jumpjack** [comment]
Thanks but I'm stuck one step before: how does the webapp know that the filename to download is myfile.dsk? I just click this link in index.hml:

    <a href="oricutron.html">myfile.dsk</a>

... and "magically" webapp receives the filename, but I don't understand how.

Unfortunately I don't know anything about wasm.
I did put some dozens of console.log() commands in oricutron.js , but I can't yet find the moment when "myfile.dsk" string is passed to webapp.

**Comment by iss000** [comment]
Not an issue.
