### ISSUE TITLE
Opcode 'and' not working

### ISSUE THREAD

**Issue by Sheld67** [pete-gordon/oricutron#189]
Hello,
I have noticed that opcode 'and' is not working on **Oricutron 1.2**.
![Oricutron_mnemonique and](https://user-images.githubusercontent.com/120820201/208255062-0488c6c9-f6a7-4557-a8dd-39b892d41290.png)
Is this something that you were already aware of?
Thanks & Best Regards.
Sheld67

**Comment by iss000** [comment]
You are using version 1.2. Whit current sources there is no problem and all works as expected.
You still can download more recent build here: https://iss.sandacite.com/iss/oricutron/
or simply build binary for your favorite OS.
