### ISSUE TITLE
Missing  LICENSE.txt - needed for package distributors.

### ISSUE THREAD

**Issue by seclorum** [pete-gordon/oricutron#198]
Hi,

The absence of the LICENSE.txt file for the repository makes the license for package builders a little unclear - I've submitted a PR[0]  for this, but wanted to open up an Issue on the license subject anyway.

I took the presence of the GPLv2 License text[1] in the source code headers to mean that the entire repository should be licensed in that manner - but I confess this may have been inadequate and other contributors may have different licenses for their contributions (e.g. package build scripts, etc.).

[0] - https://github.com/pete-gordon/oricutron/pull/197
[1] - https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

**Comment by pete-gordon** [comment]
Oricutron has always been GPLv2, and the git repo is marked as such. If anyone submitted code, they should reasonably have been expected to know it was a GPLv2 project, so I don't think there's any concern.
