### ISSUE TITLE
No exit key

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pete-gordon/oricutron#49]
```
Is it me or there is no way to exit Orictron with a simple key (ESC would be 
fine for all Arcade cabinet users for example) or a combination of keys...
```

Original issue reported on code.google.com by `o.boiss...@gmail.com` on 10 Nov 2010 at 10:20

**Comment by Godzil** [comment]
As the ESC key is a valid key for the Oric, it would not make any sense to map it to "exit", the F1 key display the Oricutron Menu, and it could be navigated with the arrow keys (enter to select) it not sufficient?

**Comment by Blonder** [comment]
On Windows Alt-F4 closes a window - works for all Windows applications also for Oricutron - no need to go into the menu.

**Comment by polluks** [comment]
Well, in Mac OS X Cmd+Q doesn't seem to work...
