### ISSUE TITLE
Copy/Paste not working on Linux since v1.2

### ISSUE THREAD

**Issue by assinie** [pete-gordon/oricutron#74]
Hi, copy/paste from/to clipboard doesn't work since v1.2 on Linux/X11 platform and hang.

* Steps to reproduce:
  1. start oricutron
  2. put something in the X11 clipboard
  3. Press [F12]
* Expected result;
  * clipboard copied to oricutron "window"

* Actual result:
   * -> oricutron goes in a never ending loop

* Environment:
  * oricutron >= 1.2 (compiled with x11 support)
  * Linux

---
Possible fix:
Change __get_clipboard_text_x11__ function line 191
from
 `XEvent* xevent = (XEvent*)event.syswm.msg;`
to
`XEvent* xevent = &event.syswm.msg->event.xevent;`

Same change in __clipboard_filter__ function line 69 (at least [F11] broken).

Or revert _xevent_ to v1.1 declaration and change all _xevent->xxx_ to _xevent.xxx_
In previuous version, xevent was:
`XEvent xevent = event.syswm.msg->event.xevent;`

Thanks a lot for this very nice emulator :+1: 

Christian from http://forum.defence-force.org
aka assinie from http://forums.oric.org

**Comment by pete-gordon** [comment]
This is now fixed.
