### ISSUE TITLE
AND mnemonic not correctly handled by monitor

### ISSUE THREAD

**Issue by assinie** [pete-gordon/oricutron#76]
Hi, **kenneth** from http://forums.oric.org raised an issue about the *AND* instruction with the monitor's assembler.

* Step to reproduce:
 1. start oricutron
 2. Press [F2] to enter monitor
 3. a $9600
 4. AND $10,X
   `9600 35 10   AND $10,X`
 5. AND #$10
  `illegal operand`

* I think issue is with lines 261 and 263 in *monitor.c* (double declaration of *AND* instruction)
>//                                          imp   imm    zp   zpx   zpy   abs   abx   aby   zix   ziy   rel   ind
>                                  { "AND",   -1,   -1,   -1, 0x35,   -1,   -1, 0x3d, 0x39, 0x21, 0x31,   -1,   -1 },
>                                  { "BIT",   -1,   -1, 0x24,   -1,   -1, 0x2c,   -1,   -1,   -1,   -1,   -1,   -1 },
>                                  { "AND",   -1, 0x29, 0x25,   -1,   -1, 0x2d,   -1,   -1,   -1,   -1,   -1,   -1 },

---
Possible fix:
Delete line 263 and replace line 261 with:
>{ "AND",   -1,   0x29,   0x25, 0x35,   -1,   0x2d, 0x3d, 0x39, 0x21, 0x31,   -1,   -1 },

**Comment by pete-gordon** [comment]
This is now fixed.
