### ISSUE TITLE
Do we want switchable menu color scheme(s)

### ISSUE THREAD

**Issue by Blonder** [pete-gordon/oricutron#84]
![20160613_oricutron_menu_color_scheme](https://cloud.githubusercontent.com/assets/309430/16018057/0dcc62d4-31a3-11e6-90f0-86a3fa751bb1.PNG)

**Comment by pete-gordon** [comment]
No objection here... :+1:

**Comment by Blonder** [comment]
Now menu colors are automatically switched based on selected machine type, see https://twitter.com/Aachen360
