### ISSUE TITLE
Reset Button NMI [F3] menu entry in Main Menu?

### ISSUE THREAD

**Issue by Blonder** [pete-gordon/oricutron#87]
Do we want the "Reset Button NMI [F3]" menu entry in the main menu and rename the "Reset" menu entry to "Hard Reset"?
![20160621_oricutron_resetbuttonnmiinmainmenu](https://cloud.githubusercontent.com/assets/309430/16243625/7339910e-37f8-11e6-947c-1fbb8ca3ef1b.PNG)

**Comment by pete-gordon** [comment]
OK

**Comment by Blonder** [comment]
68e6485bc15625a0c1444e99a383c08106f9ad2f completed.
