### ISSUE TITLE
Plugins for oricutron

### ISSUE THREAD

**Issue by jedeoric** [pete-gordon/oricutron#89]
Hello, 

is there a simple way to add an electronic extention in oricutron ?

The easiest way should be plugins in oricutron. In this way, we could reserve adress on page 3 and add handler on these address

**Comment by polluks** [comment]
I like the idea, for example [ACE](http://ace.cpcscene.net) has a nice plug-in system.

**Comment by jedeoric** [comment]
The Idea is from Philippe (ACE développer) Because i know him : We talk about CPC/Oric at the restaurant :)

**Comment by iss000** [comment]
Adding plugins to Oricutron will be great feature. It's doable but not simple to support all target platforms.
Else, if someone wants to emulate virtual hardware in page 3 (for his own purposes or fun) - there is an ugly but really simple way to do it. :)

**Comment by pete-gordon** [comment]
I had intended to put plugins into a planned rewrite of Oricutron (oricutron 2), but I don't know if I'll ever have time to actually get around to it.

**Comment by jedeoric** [comment]
I am trying to add my extension to Oricutron (without plugins). I have a problem, and i don't know where it is in the code event if i tried to understand.

I register my extension in  #340 and #341. When i try to read value in #340 into Oricutron like :
LDA $340
My code in oricutron send 128 when it call my read function in C

but in debugger, it still reads VIA value. 

I mean in debugger : #340 address contains same value located in #300.

How can i say to oricutron : OK i have something in  #340, don't send #300 value in oricutron.

In machine.c i have :
```

unsigned char telestratread( struct m6502 *cpu, unsigned short addr )
{
  struct machine *oric = (struct machine *)cpu->userdata;

  if( ( addr & 0xff00 ) == 0x0300 )
  {
    switch( addr & 0x0f0 )
    {
      case 0x010:
        if( addr >= 0x31c )
        {
          return acia_read( &oric->tele_acia, addr );
        }

        return microdisc_read( &oric->md, addr );

      case 0x020:
        return via_read( &oric->tele_via, addr );

/*My extension here*/
	 case 0x040:
		  if (addr == 0x340 || addr == 0x341)
			  return myextension_read(&oric->tele_myextension, addr);
		
    }

    return via_read( &oric->via, addr );
  }
```
***************************
this  **return myextension_read(&oric->tele_myextension, addr);** contains the right value, but debugger still have the wrong value (VIA register value is displayed)

**Comment by pete-gordon** [comment]
That looks correct. Are you verifying the extension using the debugger?

The debugger has its own read function in order avoid side effects (e.g. clearing status bits when reading the VIA).

Take a look at "monitor.c:mon_read()".

I just noticed that mon_read doesn't seem to be correct for telestrat, either, so it needs to be fixed.

**Comment by jedeoric** [comment]
Yes i am reading these from the debugger. I did not know that debugger was not reading in the same way than the emulator part.

My extension is working (a bit) now in oricutron (and should be run on atmos too, but it needs some electronic to work on real atmos)

I'll try to see debugger part too :) Thanks for the help !

**Comment by jedeoric** [comment]
plugins folder created.
