### ISSUE TITLE
Oricutron without SDL ?

### ISSUE THREAD

**Issue by jedeoric** [pete-gordon/oricutron#98]
Hello, 

I would like to run some automatic test for Orix Binary (and OriX ROM) etc.

Is it possible without some code in Oricutron ?

I mean : i would like to start Oricutron without graphics window but with a memory Dump, and stops after an event somewhere (memory or not). and save DUMP again for example.

Does someone did that in this code ?

Thanks

**Comment by jedeoric** [comment]
I forgot to say that it is not maybe the good place to ask, but i think that some people who contribute to Oricutron had started this kind of code (maybe)

**Comment by pete-gordon** [comment]
Well, there is a "null" renderer in the code, so having no gui wouldn't be a problem.

It also shouldn't be too hard to add scripting support to the monitor...

**Comment by iss000** [comment]
Hi jede, did you miss this post at DF forum: [http://forum.defence-force.org/viewtopic.php?f=22&t=1001&start=90#p15145](url) ?
If I understood correctly it's exactly what you need.

**Comment by jedeoric** [comment]
@iss000 
Hello, in fact, i never reached to have breakpoint working with the command line (i never have a look to this part of the code). I am under windows, but i have always "Invalid breakpoint"

My breakpoint file contains : 

bs 0320

I tried

bs $0320

In fact, i did a dockerfile with cc65, and i would like to have OSDK and Oricutron in this dockerfile.

The goal is to test any modification in Orix kernel/Telemon. I would like to push any Orix code under my gitlab/github  and this docker runs : 

It retrieves all Orix source code (Tools etc) from github, compile and start oricutron without SDL. Each binary compiled is tested in Orictutron. I only need to get the dump and test some address memory to see if all tool is working.
